In [46]:
import pandas as pd
import numpy as np
nocs = pd.read_csv("noc_regions.csv")
coffee = pd.read_csv("coffee.csv")
bios = pd.read_csv("bios.csv")
olympics_data = pd.read_parquet("results.parquet")

## Intro to DF

In [ ]:

df = pd.DataFrame([[1,2,3], [4,5,6], [7,8,9]], columns = ["A", 'B', "C"], index = ["x", "y", "z"])
# df.head()
# df.columns
# df
# df.index
# df.index.to_list()
# df.info()
# df.describe()
# df.nunique()
# df.shape

## Loading to DF

In [ ]:
coffee = pd.read_csv("coffee.csv")
#Below way is using the link
# coffee = pd.read_csv("https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/warmup-data/coffee.csv")

## Accessing Data with Pandas

In [ ]:
# coffee.head()
# coffee
# print(coffee)
# display(coffee)
# coffee.sample(10)
# coffee.sample(5, random_state = 1) #THis way your DF won't refresh data 

# coffee.loc[rows, columns]
# coffee.iloc[rows, columns] #only using index values
# coffee.loc[[0,1,2]]
# coffee.loc[0:3] # using slicing
# coffee.loc[0:3, ["Day", "Units Sold"]] #slicing rows and adding specific columns
# coffee.iloc[:, [0,2]] #colon represents all rows

# coffee.index = coffee["Day"] #This will change the index numbering to days as per the Days column data
#If we are going to use slicing using numbers, there will be error, as the slicing will be working based on the Days as index
# coffee.loc["Monday": "Wednesday"]

# coffee.loc[1:3, "Units Sold"] = 10 #This will edit the value on 1st row and Units Sold column
# coffee

# coffee.at[0, "Units Sold"]
# coffee.iat[0, 0]

# coffee.sort_values("Units Sold") #Sorted in ascending
# coffee.sort_values(["Units Sold", "Coffee"], ascending=False) #Sorted in descending

# for index, row in coffee.iterrows(): #Not a built-in method
#     print(index)
#     print(row)
#     print("\n")

## Filtering Data

In [ ]:
# bios.head()
# bios.info()
# bios.loc[bios['height_cm'] > 215, ['name', 'height_cm']]
# bios[bios['height_cm'] > 215] [['name', 'height_cm']] #Short Hand
# bios[(bios['height_cm'] > 215) & (bios['born_country'] == 'USA')] #Filtering based on AND Condition

# bios[bios['name'].str.contains("Ahmed")]
# bios[bios['name'].str.contains("Ahmed|patrick", case=False)]  

# bios[bios['born_country'].isin(["USA", "FRA", "GBR"])]
# bios[bios['born_country'].isin(["USA", "FRA", "GBR"]) & (bios['name'].str.startswith("Keith"))]

# bios.query('born_country == "USA" and born_city == "Seattle"') #Using query

## Adding/Removing Columns

In [ ]:
# import numpy as np
# coffee['price'] = 4.99

# coffee['new_price'] = np.where(coffee['Coffee Type']  == 'Espresso', 3.99, 5.99) #Added new column
# coffee.drop(columns = ['price']) #This drop won't remoe the column, it just returns the values at the moment, not updating changes on the data itself
# coffee.drop(columns = ['price'], inplace=True) #This drops the column and updates the table too

# coffee_new = coffee #This is referencing to the same memory as of copy
#This means that if the new variable is applied with changes, the original one will get those changes
# coffee_new = coffee.copy() #Now a new memory has been created

# coffee['revenue'] = coffee['Units Sold'] * coffee['new_price']
# coffee.rename(columns={'new_price':'price'}, inplace=True)

# # bios_new = bios.copy()
# bios_new['first_name'] = bios_new['name'].str.split(' ').str[0]

# #Extracting year only from the born_date
# #COnverting the field into datetime data type
# bios_new['born_datetime'] = pd.to_datetime(bios_new['born_date'])
# bios_new['born_year'] = bios_new['born_datetime'].dt.year
# bios_new[['name', 'born_year']]

# #Using Custom Function by Lambda
# bios['height_category'] = bios['height_cm'].apply(lambda x: 'Short' if x < 165 else ('Average' if x < 185 else 'Tall'))
# bios.head()

# #Another way of using custom functions
# def categorize_athlete(row):
#     if row['height_cm'] < 175 and row['weight_kg'] < 70:
#         return 'Lightweight'
#     elif row['height_cm'] < 185 or row['weight_kg'] <= 80:
#         return 'Middleweight'
#     else:
#         return 'Heavyweight'

# bios['Category'] = bios.apply(categorize_athlete, axis=1)
# bios

## Merging & Concatenating Data

In [ ]:
# nocs.head()
# bios_new = pd.merge(bios, nocs, left_on='born_country', right_on='NOC', how='inner', suffixes=["bios", "nocdf"])
# bios_new = pd.merge(bios, nocs, left_on='born_country', right_on='NOC', how='inner')
# bios_new.rename(columns={'region': 'born_country_full'}, inplace=True)
# bios_new[bios_new['NOC_x'] != bios_new['born_country_full']][['name', 'NOC_x', 'born_country_full']]

# usa = bios[bios['born_country']=='USA'].copy()
# gbr = bios[bios['born_country']=='GBR'].copy()

#Joining 2 DFs, one on top of another
# new_df = pd.concat([usa, gbr])
# new_df

## Handling Null Values

In [ ]:
#Making some values null to perform the operations
# coffee.loc[[2,4], 'Units Sold'] = np.nan
# coffee.head()
# coffee.info()
# coffee.isna().sum()

# coffee.fillna(coffee['Units Sold'].mean()) #One Way
# coffee.fillna(coffee['Units Sold'].interpolate()) #2nd Way

# coffee['Units Sold'] = coffee['Units Sold'].interpolate()

#Dropping na Rows
# coffee.dropna(subset=['Units Sold'], inplace=True)
#Filtering na values
# coffee[coffee['Units Sold'].notna()]

# coffee.head()

          Day Coffee Type  Units Sold
0      Monday    Espresso        25.0
1      Monday       Latte        15.0
3     Tuesday       Latte        20.0
5   Wednesday       Latte        25.0
6    Thursday    Espresso        40.0
7    Thursday       Latte        30.0
8      Friday    Espresso        45.0
9      Friday       Latte        35.0
10   Saturday    Espresso        45.0
11   Saturday       Latte        35.0
12     Sunday    Espresso        45.0
13     Sunday       Latte        35.0

## Aggregating Data

In [79]:
# bios[bios['born_country']=='USA']['born_region'].value_counts()

# coffee['Units Sold'] = coffee['Units Sold'].interpolate()
# coffee.groupby(['Coffee Type'])['Units Sold'].sum()
# coffee.groupby(['Coffee Type'])['Units Sold'].mean()
# coffee.groupby(['Coffee Type']).agg({'Units Sold': 'sum', 'price': 'mean'})

#2nd way of aggregating
# pivot = coffee.pivot(columns='Coffee Type', index='Day', values='revenue')
# pivot.sum()
# pivot.sum(axis=1) #Will sum based on each row data


bios['born_date'] = pd.to_datetime(bios['born_date'])
# bios.groupby(bios['born_date'].dt.year).count()
bios.groupby(bios['born_date'].dt.year)['name'].count().reset_index().sort_values('name', ascending=False)

bios['month_born'] = bios['born_date'].dt.month
bios['year_born'] = bios['born_date'].dt.year
bios.groupby([bios['year_born'],bios['month_born']])['name'].count().reset_index().sort_values('name', ascending=False)

      year_born  month_born  name
1437     1970.0         1.0   239
1461     1972.0         1.0   229
1497     1975.0         1.0   227
1629     1986.0         1.0   227
1617     1985.0         1.0   225
...         ...         ...   ...
1877     2006.0        12.0     1
1871     2006.0         3.0     1
20       1846.0         7.0     1
21       1846.0         8.0     1
22       1846.0         9.0     1

[1885 rows x 3 columns]

## Advanced Functionality

In [92]:
# .shift() .rank() .rolling() .cumsum()

# coffee['yesterday_revenue'] = coffee['revenue'].shift(2)
# coffee['pct_change'] = coffee['revenue'] / coffee['yesterday_revenue'] * 100
# coffee

# bios['height_rank'] = bios['height_cm'].rank()
# bios['height_rank'].sort_values(ascending=False)
# bios.sort_values(['height_rank'])

# coffee.select_dtypes('float').cumsum().reset_index()
coffee['cumulative_revenue'] = coffee['revenue'].cumsum()
latte = coffee[coffee['Coffee Type']=="Latte"].copy()
latte['3day'] = latte['Units Sold'].rolling(3).sum()
latte

,Day,Coffee Type,Units Sold,price,revenue,yesterday_revenue,pct_change,cumulative_revenue,3day
1,Monday,Latte,15,5.99,89.85,NaN,NaN,189.6,NaN
3,Tuesday,Latte,20,5.99,119.80,89.85,133.333333,429.1,NaN
5,Wednesday,Latte,25,5.99,149.75,119.80,125.000000,718.5,60.0
7,Thursday,Latte,30,5.99,179.70,149.75,120.000000,1057.8,75.0
9,Friday,Latte,35,5.99,209.65,179.70,116.666667,1447.0,90.0
11,Saturday,Latte,35,5.99,209.65,209.65,100.000000,1836.2,100.0
13,Sunday,Latte,35,5.99,209.65,209.65,100.000000,2225.4,105.0