In [ ]:
import pandas as pd

# coffee = pd.read_csv("coffee.csv")
bios = pd.read_csv("bios.csv")
olympics_data = pd.read_parquet("results.parquet")

## Intro to DF

In [ ]:

df = pd.DataFrame([[1,2,3], [4,5,6], [7,8,9]], columns = ["A", 'B', "C"], index = ["x", "y", "z"])
# df.head()
# df.columns
# df
# df.index
# df.index.to_list()
# df.info()
# df.describe()
# df.nunique()
# df.shape

(3, 3)

## Loading to DF

In [152]:
coffee = pd.read_csv("coffee.csv")
#Below way is using the link
# coffee = pd.read_csv("https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/warmup-data/coffee.csv")

## Accessing Data with Pandas

In [ ]:
# coffee.head()
# coffee
# print(coffee)
# display(coffee)
# coffee.sample(10)
# coffee.sample(5, random_state = 1) #THis way your DF won't refresh data 

# coffee.loc[rows, columns]
# coffee.iloc[rows, columns] #only using index values
# coffee.loc[[0,1,2]]
# coffee.loc[0:3] # using slicing
# coffee.loc[0:3, ["Day", "Units Sold"]] #slicing rows and adding specific columns
# coffee.iloc[:, [0,2]] #colon represents all rows

# coffee.index = coffee["Day"] #This will change the index numbering to days as per the Days column data
#If we are going to use slicing using numbers, there will be error, as the slicing will be working based on the Days as index
# coffee.loc["Monday": "Wednesday"]

# coffee.loc[1:3, "Units Sold"] = 10 #This will edit the value on 1st row and Units Sold column
# coffee

# coffee.at[0, "Units Sold"]
# coffee.iat[0, 0]

# coffee.sort_values("Units Sold") #Sorted in ascending
# coffee.sort_values(["Units Sold", "Coffee"], ascending=False) #Sorted in descending

# for index, row in coffee.iterrows(): #Not a built-in method
#     print(index)
#     print(row)
#     print("\n")

0
Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object


1
Day            Monday
Coffee Type     Latte
Units Sold         10
Name: 1, dtype: object


2
Day             Tuesday
Coffee Type    Espresso
Units Sold           10
Name: 2, dtype: object


3
Day            Tuesday
Coffee Type      Latte
Units Sold          10
Name: 3, dtype: object


4
Day            Wednesday
Coffee Type     Espresso
Units Sold            35
Name: 4, dtype: object


5
Day            Wednesday
Coffee Type        Latte
Units Sold            25
Name: 5, dtype: object


6
Day            Thursday
Coffee Type    Espresso
Units Sold           40
Name: 6, dtype: object


7
Day            Thursday
Coffee Type       Latte
Units Sold           30
Name: 7, dtype: object


8
Day              Friday
Coffee Type    Espresso
Units Sold           45
Name: 8, dtype: object


9
Day            Friday
Coffee Type     Latte
Units Sold         35
Name: 9, dtype: object


10
Day            Saturday
Coffee Type    Espresso
Units Sold           45
Name: 10, dtype: object


11
Day            Saturday
Coffee Type       Latte
Units Sold           35
Name: 11, dtype: object


12
Day              Sunday
Coffee Type    Espresso
Units Sold           45
Name: 12, dtype: object


13
Day            Sunday
Coffee Type     Latte
Units Sold         35
Name: 13, dtype: object

## Filtering Data

In [ ]:
# bios.head()
# bios.info()
# bios.loc[bios['height_cm'] > 215, ['name', 'height_cm']]
# bios[bios['height_cm'] > 215] [['name', 'height_cm']] #Short Hand
# bios[(bios['height_cm'] > 215) & (bios['born_country'] == 'USA')] #Filtering based on AND Condition

# bios[bios['name'].str.contains("Ahmed")]
# bios[bios['name'].str.contains("Ahmed|patrick", case=False)]  

# bios[bios['born_country'].isin(["USA", "FRA", "GBR"])]
# bios[bios['born_country'].isin(["USA", "FRA", "GBR"]) & (bios['name'].str.startswith("Keith"))]

# bios.query('born_country == "USA" and born_city == "Seattle"') #Using query

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
11030,11088,David Halpern,1955-08-18,Seattle,Washington,USA,United States,178.0,79.0,NaN
12800,12870,Todd Trewin,1958-04-20,Seattle,Washington,USA,United States,180.0,75.0,NaN
15476,15583,Scott McKinley,1968-10-15,Seattle,Washington,USA,United States,183.0,75.0,NaN
29079,29293,Joyce Tanac,1950-09-27,Seattle,Washington,USA,United States,156.0,49.0,NaN
31135,31371,Bill Kuhlemeier,1908-01-14,Seattle,Washington,USA,United States,NaN,NaN,2001-07-08
...,...,...,...,...,...,...,...,...,...,...
133392,136331,Hans Struzyna,1989-03-31,Seattle,Washington,USA,United States,188.0,91.0,NaN
135448,138662,Maude Davis Crossland,2003-03-19,Seattle,Washington,USA,Colombia,NaN,NaN,NaN
136993,140229,Jenell Berhorst,2003-12-13,Seattle,Washington,USA,United States,NaN,NaN,NaN
143507,147159,Nevin Harrison,2002-06-02,Seattle,Washington,USA,United States,175.0,73.0,NaN
145446,149169,Corinne Stoddard,2001-08-15,Seattle,Washington,USA,United States,NaN,NaN,NaN

## Adding/Removing Columns

In [153]:
import numpy as np
coffee['price'] = 4.99

# coffee['new_price'] = np.where(coffee['Coffee Type']  == 'Espresso', 3.99, 5.99) #Added new column
# coffee.drop(columns = ['price']) #This drop won't remoe the column, it just returns the values at the moment, not updating changes on the data itself
# coffee.drop(columns = ['price'], inplace=True) #THis drops the column and updates th table too
coffee

          Day Coffee Type  Units Sold  price
0      Monday    Espresso          25   4.99
1      Monday       Latte          15   4.99
2     Tuesday    Espresso          30   4.99
3     Tuesday       Latte          20   4.99
4   Wednesday    Espresso          35   4.99
5   Wednesday       Latte          25   4.99
6    Thursday    Espresso          40   4.99
7    Thursday       Latte          30   4.99
8      Friday    Espresso          45   4.99
9      Friday       Latte          35   4.99
10   Saturday    Espresso          45   4.99
11   Saturday       Latte          35   4.99
12     Sunday    Espresso          45   4.99
13     Sunday       Latte          35   4.99